apiVersion: v2
name: harvester-crd
version: 0.0.0-master-0ed87520
appVersion: master-0ed87520
description: Helm chart for deploying Harvester CRDs.
icon: https://harvester.github.io/images/logo_horizontal.svg
keywords:
  - virtualization
  - HCI
home: https://github.com/harvester/harvester
sources:
  - https://github.com/harvester/harvester
